---
- name: Install Pulsar Server
  hosts: "{{ lookup('env', 'variable_host') | default('localhost', true) }}" # workaround because SRC needs localhost, but molecule needs specifc hostvars

  pre_tasks:
    # Copied from mirelaminkova/src-component-galaxy
    - name: Set workspace user facts
      ansible.builtin.include_role:
        name: uusrc.general.fact_regular_users

    - name: Install Dependencies
      ansible.builtin.apt:
        update_cache: true
        name:
          - build-essential
          - git
          - libcurl4-openssl-dev
          - libssl-dev
          - python3-psycopg2
          - python3-virtualenv
          - python3-dev
          - acl
          - gnutls-bin # workaround for git-clone issue, https://stackoverflow.com/a/53147659/4326632
        state: present

  roles:
    - galaxyproject.cvmfs
    - usegalaxy_eu.apptainer
    - uusrc.general.nginx_reverse_proxy
    - galaxyproject.repos
    # https://github.com/galaxyproject/pulsar/issues/375
    - galaxyproject.slurm
    - galaxyproject.pulsar

  post_tasks:
    - name: Create directory /srv/static/
      file:
        path: /srv/static/
        state: directory
        mode: '0755'

    - name: Template out the welcome
      template:
        src: templates/welcome.html
        dest: /srv/static/index.html
        owner: root
        group: root
        mode: '0644'
